routes/web.php
<?php

use App\Http\Controllers\AccountingNotebookController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\InvoicesDetaillsController;
use App\Http\Controllers\BoxController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\InvoicesController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\InvoiceAttachmentsTableController;
use App\Http\Controllers\Invoices_Report;
use App\Http\Controllers\Customers_Report;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LiquidationStatusController;
use App\Http\Controllers\MyAccountantsController;
use App\Http\Controllers\SendToController;


Route::get('/', function () {
     return view('auth.login'); });

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->middleware('auth')->name('home');

Route::post('search_by_date', [HomeController::class, 'search_by_date'])->middleware('auth')->name('home.search.invoices');


Route::resource('invoice_attachments_table', InvoiceAttachmentsTableController::class);

Route::controller(InvoicesDetaillsController::class)->group( function () {
        Route::get('/InvoicesDetails/{id}', 'edit');

        Route::get('download/{invoice_number}/{file_name}', 'get_file');

        Route::get('View_file/{invoice_number}/{file_name}', 'open_file');

        Route::post('delete_file', 'destroy')->name('delete_file');
        }
);

Route::resource('invoices',InvoicesController::class);
// Route::get('/edit_getfile/{id}', [InvoicesController::class,'getfile']);

Route::controller(InvoicesController::class)->group( function () {


        Route::get('/edit_invoice/{id}', 'edit');

        Route::get('/Status_show/{id}', 'show')->name('Status_show');

        Route::post('/Status_Update/{id}', 'Status_Update')->name('Status_Update');

        Route::get('Invoice_Paid','Invoice_Paid');

        Route::get('Invoice_UnPaid','Invoice_UnPaid');

        Route::get('Print_invoice/{id}','Print_invoice');

        Route::get('export_invoices','export');


    }
);

Route::controller(Invoices_Report::class)->group( function () {

        Route::get('invoices_report','index');

        Route::post('Search_invoices','Search_invoices');

        Route::post('export_report_pdf','export_report_pdf')->name('export_report_pdf.pdf');

        Route::get('paid_invoices','paid_invoices');

        Route::get('unpaid_invoices','unpaid_invoices');

    }
);

Route::post('Search_customers', [Customers_Report::class,'Search_customers']);

Route::group(['middleware' => ['auth']], function() {

    Route::resource('roles',RoleController::class);

    Route::resource('users',UserController::class);
});

///////////////////////////////////Start AccountingNotebook Route/////////////////////////////////////
Route::group(['prefix' => 'AccountingNotebook'] , function() {


    // Route::get('/index' , [AccountingNotebookController::class , 'index'])->name('AccountingNotebook.index') ;

    Route::get('/create' , [AccountingNotebookController::class , 'create'])->name('AccountingNotebook.create') ;

    Route::post('/store' , [AccountingNotebookController::class , 'store'])->name('AccountingNotebook.store') ;

    Route::get('/edit/{id}' , [AccountingNotebookController::class , 'edit'])->name('AccountingNotebook.edit') ;

    Route::post('/update' , [AccountingNotebookController::class , 'update'])->name('AccountingNotebook.update') ;

    Route::get('/delete/{id}' , [AccountingNotebookController::class , 'destroy'])->name('AccountingNotebook.delete') ;

    Route::post('search', [AccountingNotebookController::class , 'search_in_accounting'])->name('search_in_accounting');


    // Start Box
    // Route::get('/' , [LanguageController::class , 'index'])->name('admin.language.index') ;

    Route::group([ 'prefix' =>   'box'] , function()    {

        Route::get('/' , [BoxController::class , 'index'])->name('AccountingNotebook.box.index') ;

        Route::get('/create' , [BoxController::class , 'create'])->name('AccountingNotebook.box.create') ;

        Route::post('store' , [BoxController::class , 'store'])->name('AccountingNotebook.box.store') ;

        Route::get('edit/{id}' , [BoxController::class , 'edit'])->name('AccountingNotebook.box.edit') ;

        Route::post('update' , [BoxController::class , 'update'])->name('AccountingNotebook.box.update') ;

        Route::get('/delete/{id}' , [BoxController::class , 'destroy'])->name('AccountingNotebook.box.delete') ;
    }) ;
    // End Box


    // Start SendTo
    Route::group([ 'prefix' =>   'SendTo'] , function()    {

        Route::get('/' , [SendToController::class , 'index'])->name('AccountingNotebook.SendTo.index') ;

        Route::get('/create' , [SendToController::class , 'create'])->name('AccountingNotebook.SendTo.create') ;

        Route::post('store' , [SendToController::class , 'store'])->name('AccountingNotebook.SendTo.store') ;

        Route::get('edit/{id}' , [SendToController::class , 'edit'])->name('AccountingNotebook.SendTo.edit') ;

        Route::post('update' , [SendToController::class , 'update'])->name('AccountingNotebook.SendTo.update') ;

        Route::get('/delete/{id}' , [SendToController::class , 'destroy'])->name('AccountingNotebook.SendTo.delete') ;
    }) ;
    // End SendTo


    // Start LiquidationStatus
    Route::group([ 'prefix' =>   'LiquidationStatus'] , function()    {

        Route::get('/' , [LiquidationStatusController::class , 'index'])->name('AccountingNotebook.LiquidationStatus.index') ;

        Route::get('/create' , [LiquidationStatusController::class , 'create'])->name('AccountingNotebook.LiquidationStatus.create') ;

        Route::post('store' , [LiquidationStatusController::class , 'store'])->name('AccountingNotebook.LiquidationStatus.store') ;

        Route::get('edit/{id}' , [LiquidationStatusController::class , 'edit'])->name('AccountingNotebook.LiquidationStatus.edit') ;

        Route::post('update' , [LiquidationStatusController::class , 'update'])->name('AccountingNotebook.LiquidationStatus.update') ;

        Route::get('/delete/{id}' , [LiquidationStatusController::class , 'destroy'])->name('AccountingNotebook.LiquidationStatus.delete') ;
    }) ;
})  ;
    // #end LiquidationStatus

     // Start Company
Route::prefix('company')->name('company.')->group(function () {

    Route::get('/', [CompanyController::class,'index'])->name('allcompany');

    Route::get('/add-Company', [CompanyController::class,'create'])->name('addCompany');

    Route::post('/add-Company', [CompanyController::class,'store'])->name('addCompany');

    Route::get('/edit-Company/{id}', [CompanyController::class,'edit'])->name('editCompany');

    Route::post('/update-company', [CompanyController::class,'update'])->name('updateCompany');

    Route::get('/delete-company/{id}', [CompanyController::class,'destroy'])->name('destroycompany');
});
    // #end Company

         // Start dftar
    Route::get('/myaccountants', [MyAccountantsController::class,'index'])->name('myaccountants');

    Route::post('/add-myaccountants', [MyAccountantsController::class,'store'])->name('myaccountants.store');

    Route::get('/edit-myaccountants/{id}', [MyAccountantsController::class,'edit'])->name('myaccountants.edit');

    Route::post('/update-myaccountants', [MyAccountantsController::class,'update'])->name('myaccountants.update');

    Route::get('/delete-myaccountants/{id}', [MyAccountantsController::class,'destroy'])->name('myaccountants.delete');

    Route::get('/myaccountants/accountingnotebook/{id}', [MyAccountantsController::class,'create'])->name('addmyaccountants');

    Route::get('/allaccountingnotebook/{id}', [MyAccountantsController::class,'show'])->name('allaccountingnotebook.show');

    // #end dftar

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;
class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;
    /**
    * The attributes that are mass assignable.
    *
    * @var array
    */
    protected $fillable = [
    'name', 'email', 'password','roles_name','Status'
    ];
    /**
    * The attributes that should be hidden for arrays.
    *
    * @var array
    */
    protected $hidden = [
    'password', 'remember_token',
    ];
    /**
    * The attributes that should be cast to native types.
    *
    * @var array
    */
    protected $casts = [
    'email_verified_at' => 'datetime',
    'roles_name' => 'array',

    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;


class UserController extends Controller
{

    public function __construct()
    {
        $this->middleware('can:قائمة المستخدمين', ['only' => ['index']]);
        // $this->middleware('can:اضافة مستخدم', ['only' => ['create', 'store']]);
        // $this->middleware('can:تعديل مستخدم', ['only' => ['edit', 'update']]);
        // $this->middleware('can:حذف مستخدم', ['only' => ['destroy']]);
    }

    public function index(Request $request)

    {

        $data = User::orderBy('id', 'DESC')->paginate(5);

        return view('users.show_users', compact('data'))

            ->with('i', ($request->input('page', 1) - 1) * 5);
    }

    public function create()

    {

        $roles = Role::pluck('name', 'name')->all();

        return view('users.Add_user', compact('roles'));
    }

    public function store(Request $request)

    {

        $request->validate([
            'name' => 'required',
            'email' => 'required|email|unique:users,email',
            'password' => 'required|same:confirm-password',
            'roles_name' => 'required'
        ]);

        $input = $request->all();
        $input['password'] = Hash::make($input['password']);
        $user = User::create($input);
        $user->assignRole($request->input('roles_name'));
        return redirect()->route('users.index')
            ->with('success', 'تم اضافة المستخدم بنجاح');
    }

    public function show($id)

    {

        $user = User::find($id);
        return view('users.show', compact('user'));
    }

    public function edit($id)

    {

        $user = User::find($id);
        $roles = Role::pluck('name', 'name')->all();
        $userRole = $user->roles->pluck('name', 'name')->all();
        return view('users.edit', compact('user', 'roles', 'userRole'));
    }

    public function update(Request $request, $id)

    {

        $request->validate([
            'name' => 'required',
            'email' => 'required|email|unique:users,email,' . $id,
            'password' => 'required|same:confirm-password',
            'roles' => 'required'
        ]);
        $input = $request->all();
        if (!empty($input['password'])) {
            $input['password'] = Hash::make($input['password']);
        } else {
            $input = array_except($input, array('password'));
        }
        $user = User::find($id);
        $user->update($input);
        DB::table('model_has_roles')->where('model_id', $id)->delete();
        $user->assignRole($request->input('roles'));
        return redirect()->route('users.index')
            ->with('success', 'تم تحديث معلومات المستخدم بنجاح');
    }

    public function destroy(Request $request)

    {

        User::find($request->user_id)->delete();
        return redirect()->route('users.index')->with('success', 'تم حذف المستخدم بنجاح');
    }
}

resources/views/users/edit_company.blade.php
@extends('layouts.master')
@section('css')
    <!-- Internal Nice-select css  -->
    <link href="{{ URL::asset('assets/plugins/jquery-nice-select/css/nice-select.css') }}" rel="stylesheet" />
@section('title')
    تعديل شركات
@stop


@endsection
@section('page-header')
<!-- breadcrumb -->
<div class="breadcrumb-header justify-content-between">
    <div class="my-auto">
        <div class="d-flex">
            <h4 class="content-title mb-0 my-auto">الشركات</h4><span class="text-muted mt-1 tx-13 mr-2 mb-0">/ تعديل
                شركة</span>
        </div>
    </div>
</div>
<!-- breadcrumb -->
@endsection
@section('content')
@if (session()->has('message'))
<div class="alert alert-success">
    {{ session()->get('message') }}
</div>
@endif
<!-- row -->
<div class="row">
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-right">
                        <a class="btn btn-primary btn-sm" href="{{ route('company.allcompany') }}">رجوع</a>
                    </div>
                </div><br>

                <form action="{{ route('company.updateCompany') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" name="id" id="id" value="{{ $company->id }}">
                    {{-- 1 --}}

                        <div class="control-group form-group">
                            <label for="inputName" class="control-label">اسم شركة </label>
                            <input type="text" class="form-control" id="name" name="name"
                                value="{{ $company->name }}">
                        </div>



                        <div class="control-group form-group">
                            <label for="inputName" class="control-label"> ايميل الشركة </label>
                            <input type="text" class="form-control" id="email" name="email"
                                value="{{ $company->email }}">
                        </div>



                        <div class="control-group form-group">
                            <label for="inputName" class="control-label"> رقم الهاتف </label>
                            <input type="text" class="form-control" id="phone" name="phone"
                                value="{{ $company->phone }}">
                        </div>



                        <div class="control-group form-group">
                            <label for="inputName" class="control-label"> العنوان </label>
                            <input type="text" class="form-control" id="location" name="location"
                                value="{{ $company->location }}">
                        </div>



                        <div class="control-group form-group">
                            <label for="inputName" class="control-label"> رقم الشركة المرجعي </label>
                            <input type="text" class="form-control" id="ref_num" name="ref_num"
                                value="{{ $company->ref_num }}">
                        </div>



                        <div class="control-group form-group">
                            <label for="inputName" class="control-label"> معلومات اكثر عن شركة </label>
                            <input type="text" class="form-control" id="details" name="details"
                                value="{{ $company->details }}">
                        </div>





                    <div class="d-flex justify-content-center">
                        <button type="submit" class="btn btn-success">حفظ البيانات</button>
                    </div>

                </form>

            </div>
        </div>
    </div>
</div>




</div>
<!-- row closed -->
</div>
<!-- Container closed -->
</div>
<!-- main-content closed -->
@endsection
@section('js')

<!-- Internal Nice-select js-->
<script src="{{ URL::asset('assets/plugins/jquery-nice-select/js/jquery.nice-select.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/jquery-nice-select/js/nice-select.js') }}"></script>

<!--Internal  Parsley.min js -->
<script src="{{ URL::asset('assets/plugins/parsleyjs/parsley.min.js') }}"></script>
<!-- Internal Form-validation js -->
<script src="{{ URL::asset('assets/js/form-validation.js') }}"></script>
@endsection

resources/views/users/show_company.blade.php
@extends('layouts.master')
@section('css')

@section('title')
    الشركات
@stop

<!-- Internal Data table css -->

<link href="{{ URL::asset('assets/plugins/datatable/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet" />
<link href="{{ URL::asset('assets/plugins/datatable/css/buttons.bootstrap4.min.css') }}" rel="stylesheet">
<link href="{{ URL::asset('assets/plugins/datatable/css/responsive.bootstrap4.min.css') }}" rel="stylesheet" />
<link href="{{ URL::asset('assets/plugins/datatable/css/jquery.dataTables.min.css') }}" rel="stylesheet">
<link href="{{ URL::asset('assets/plugins/datatable/css/responsive.dataTables.min.css') }}" rel="stylesheet">
<!--Internal   Notify -->
<link href="{{ URL::asset('assets/plugins/notify/css/notifIt.css') }}" rel="stylesheet" />

@endsection
@section('page-header')
<!-- breadcrumb -->
<div class="breadcrumb-header justify-content-between">
    <div class="my-auto">
        <div class="d-flex">
            <h4 class="content-title mb-0 my-auto">الشركات</h4><span class="text-muted mt-1 tx-13 mr-2 mb-0">/ قائمة
                الشركات</span>
        </div>
    </div>
</div>
<!-- breadcrumb -->
@endsection

@section('content')

@if (session()->has('message'))
<div class="alert alert-success">
    {{ session()->get('message') }}
</div>
@endif

<!-- row opened -->
<div class="row row-sm">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-header pb-0">
                <div class="col-sm-1 col-md-2">

                    <a class="btn btn-primary btn-sm" href="{{ route('company.addCompany') }}">اضافة شركة</a>

                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive hoverable-table">
                    <table class="table table-hover" id="example1" data-page-length='50' style=" text-align: center;">
                        <thead>
                            <tr>
                                <th class="wd-10p border-bottom-0">#</th>
                                <th class="wd-15p border-bottom-0">اسم الشركة</th>
                                <th class="wd-20p border-bottom-0">البريد الالكتروني</th>
                                <th class="wd-15p border-bottom-0"> رقم الهاتف </th>
                                <th class="wd-15p border-bottom-0">العنوان </th>
                                <th class="wd-10p border-bottom-0"> معلمات اكثر عن شركة </th>
                                <th class="wd-10p border-bottom-0">العمليات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($companyes as $key => $company)
                                <tr>
                                    <td>{{ $company->id }}</td>
                                    <td>{{ $company->name }}</td>
                                    <td>{{ $company->email }}</td>
                                    <td>{{ $company->phone }}</td>
                                    <td>{{ $company->location }}</td>
                                    <td>{{ $company->details }}</td>
                                    <td>

                                        <a href="{{ route('company.editCompany', $company->id) }}"
                                            class="btn btn-sm btn-info" title="تعديل"><i class="las la-pen"></i></a>
                                        <a href="{{ route('company.destroycompany', $company->id) }}"
                                            class="btn btn-sm btn-danger" title="حذف نهائي"><i
                                                class="las la-trash-alt"></i></a>

                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!--/div-->

    <!-- Modal effects -->
    <div class="modal" id="modaldemo8">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content modal-content-demo">
                <div class="modal-header">
                    <h6 class="modal-title">حذف المستخدم</h6><button aria-label="Close" class="close"
                        data-dismiss="modal" type="button"><span aria-hidden="true">&times;</span></button>
                </div>
                <form action="{{ route('users.destroy', 'test') }}" method="post">
                    {{ method_field('delete') }}
                    {{ csrf_field() }}
                    <div class="modal-body">
                        <p>هل انت متاكد من عملية الحذف ؟</p><br>
                        <input type="hidden" name="user_id" id="user_id" value="">
                        <input class="form-control" name="username" id="username" type="text" readonly>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">الغاء</button>
                        <button type="submit" class="btn btn-danger">تاكيد</button>
                    </div>
            </div>
            </form>
        </div>
    </div>
</div>

</div>
<!-- /row -->
</div>
<!-- Container closed -->
</div>
<!-- main-content closed -->
@endsection
@section('js')
<!-- Internal Data tables -->
<script src="{{ URL::asset('assets/plugins/datatable/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/datatable/js/dataTables.dataTables.min.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/datatable/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/datatable/js/responsive.dataTables.min.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/datatable/js/jquery.dataTables.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/datatable/js/dataTables.bootstrap4.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/datatable/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/datatable/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/datatable/js/responsive.bootstrap4.min.js') }}"></script>
<!--Internal  Datatable js -->
<script src="{{ URL::asset('assets/js/table-data.js') }}"></script>
<!--Internal  Notify js -->
<script src="{{ URL::asset('assets/plugins/notify/js/notifIt.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/notify/js/notifit-custom.js') }}"></script>
<!-- Internal Modal js-->
<script src="{{ URL::asset('assets/js/modal.js') }}"></script>

<script>
    $('#modaldemo8').on('show.bs.modal', function(event) {
        var button = $(event.relatedTarget)
        var user_id = button.data('user_id')
        var username = button.data('username')
        var modal = $(this)
        modal.find('.modal-body #user_id').val(user_id);
        modal.find('.modal-body #username').val(username);
    })
</script>


@endsection

resources/views/users/show_users.blade.php
@extends('layouts.master')
@section('css')

@section('title')
    المستخدمين
@stop

<!-- Internal Data table css -->

<link href="{{ URL::asset('assets/plugins/datatable/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet" />
<link href="{{ URL::asset('assets/plugins/datatable/css/buttons.bootstrap4.min.css') }}" rel="stylesheet">
<link href="{{ URL::asset('assets/plugins/datatable/css/responsive.bootstrap4.min.css') }}" rel="stylesheet" />
<link href="{{ URL::asset('assets/plugins/datatable/css/jquery.dataTables.min.css') }}" rel="stylesheet">
<link href="{{ URL::asset('assets/plugins/datatable/css/responsive.dataTables.min.css') }}" rel="stylesheet">
<!--Internal   Notify -->
<link href="{{ URL::asset('assets/plugins/notify/css/notifIt.css') }}" rel="stylesheet" />

@endsection
@section('page-header')
<!-- breadcrumb -->
<div class="breadcrumb-header justify-content-between">
    <div class="my-auto">
        <div class="d-flex">
            <h4 class="content-title mb-0 my-auto">المستخدمين</h4><span class="text-muted mt-1 tx-13 mr-2 mb-0">/ قائمة
                المستخدمين</span>
        </div>
    </div>
</div>
<!-- breadcrumb -->
@endsection

@section('content')
<!-- row opened -->
<div class="row row-sm">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-header pb-0">
                <div class="col-sm-1 col-md-2">
                        <a class="btn btn-primary btn-sm" href="{{ route('users.create') }}">اضافة مستخدم</a>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive hoverable-table">
                    <table class="table table-hover" id="example1" data-page-length='50' style=" text-align: center;">
                        <thead>
                            <tr>
                                <th class="wd-10p border-bottom-0">#</th>
                                <th class="wd-15p border-bottom-0">اسم المستخدم</th>
                                <th class="wd-20p border-bottom-0">البريد الالكتروني</th>
                                <th class="wd-15p border-bottom-0">حالة المستخدم</th>
                                <th class="wd-15p border-bottom-0">نوع المستخدم</th>
                                <th class="wd-10p border-bottom-0">العمليات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($data as $key => $user)
                                <tr>
                                    <td>{{ ++$i }}</td>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>
                                        @if ($user->Status == 'مفعل')
                                            <span class="label text-success d-flex">
                                                <div class="dot-label bg-success ml-1"></div>{{ $user->Status }}
                                            </span>
                                        @else
                                            <span class="label text-danger d-flex">
                                                <div class="dot-label bg-danger ml-1"></div>{{ $user->Status }}
                                            </span>
                                        @endif
                                    </td>

                                    <td>
                                        @if (!empty($user->getRoleNames()))
                                            @foreach ($user->getRoleNames() as $v)
                                                <label class="badge badge-success">{{ $v }}</label>
                                            @endforeach
                                        @endif
                                    </td>

                                    <td>
                                            <a href="{{ route('users.edit', $user->id) }}" class="btn btn-sm btn-info"
                                                title="تعديل"><i class="las la-pen"></i></a>

                                            <a class="modal-effect btn btn-sm btn-danger" data-effect="effect-scale"
                                                data-user_id="{{ $user->id }}" data-username="{{ $user->name }}"
                                                data-toggle="modal" href="#modaldemo8" title="حذف"><i
                                                    class="las la-trash"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!--/div-->

    <!-- Modal effects -->
    <div class="modal" id="modaldemo8">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content modal-content-demo">
                <div class="modal-header">
                    <h6 class="modal-title">حذف المستخدم</h6><button aria-label="Close" class="close"
                        data-dismiss="modal" type="button"><span aria-hidden="true">&times;</span></button>
                </div>
                <form action="{{ route('users.destroy', 'test') }}" method="post">
                    {{ method_field('delete') }}
                    {{ csrf_field() }}
                    <div class="modal-body">
                        <p>هل انت متاكد من عملية الحذف ؟</p><br>
                        <input type="hidden" name="user_id" id="user_id" value="">
                        <input class="form-control" name="username" id="username" type="text" readonly>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">الغاء</button>
                        <button type="submit" class="btn btn-danger">تاكيد</button>
                    </div>
            </div>
            </form>
        </div>
    </div>
</div>

</div>
<!-- /row -->
</div>
<!-- Container closed -->
</div>
<!-- main-content closed -->
@endsection
@section('js')
<!-- Internal Data tables -->
<script src="{{ URL::asset('assets/plugins/datatable/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/datatable/js/dataTables.dataTables.min.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/datatable/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/datatable/js/responsive.dataTables.min.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/datatable/js/jquery.dataTables.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/datatable/js/dataTables.bootstrap4.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/datatable/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/datatable/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/datatable/js/responsive.bootstrap4.min.js') }}"></script>
<!--Internal  Datatable js -->
<script src="{{ URL::asset('assets/js/table-data.js') }}"></script>
<!--Internal  Notify js -->
<script src="{{ URL::asset('assets/plugins/notify/js/notifIt.js') }}"></script>
<script src="{{ URL::asset('assets/plugins/notify/js/notifit-custom.js') }}"></script>
<!-- Internal Modal js-->
<script src="{{ URL::asset('assets/js/modal.js') }}"></script>

<script>
    $('#modaldemo8').on('show.bs.modal', function(event) {
        var button = $(event.relatedTarget)
        var user_id = button.data('user_id')
        var username = button.data('username')
        var modal = $(this)
        modal.find('.modal-body #user_id').val(user_id);
        modal.find('.modal-body #username').val(username);
    })

</script>


@endsection