routes/web.php
<?php

use App\Http\Controllers\AccountingNotebookController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\InvoicesDetaillsController;
use App\Http\Controllers\BoxController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\InvoicesController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\InvoiceAttachmentsTableController;
use App\Http\Controllers\Invoices_Report;
use App\Http\Controllers\Customers_Report;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LiquidationStatusController;
use App\Http\Controllers\MyAccountantsController;
use App\Http\Controllers\SendToController;


Route::get('/', function () {
     return view('auth.login'); });

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->middleware('auth')->name('home');

Route::post('search_by_date', [HomeController::class, 'search_by_date'])->middleware('auth')->name('home.search.invoices');


Route::resource('invoice_attachments_table', InvoiceAttachmentsTableController::class);

Route::controller(InvoicesDetaillsController::class)->group( function () {
        Route::get('/InvoicesDetails/{id}', 'edit');

        Route::get('download/{invoice_number}/{file_name}', 'get_file');

        Route::get('View_file/{invoice_number}/{file_name}', 'open_file');

        Route::post('delete_file', 'destroy')->name('delete_file');
        }
);

Route::resource('invoices',InvoicesController::class);
// Route::get('/edit_getfile/{id}', [InvoicesController::class,'getfile']);

Route::controller(InvoicesController::class)->group( function () {


        Route::get('/edit_invoice/{id}', 'edit');

        Route::get('/Status_show/{id}', 'show')->name('Status_show');

        Route::post('/Status_Update/{id}', 'Status_Update')->name('Status_Update');

        Route::get('Invoice_Paid','Invoice_Paid');

        Route::get('Invoice_UnPaid','Invoice_UnPaid');

        Route::get('Print_invoice/{id}','Print_invoice');

        Route::get('export_invoices','export');


    }
);

Route::controller(Invoices_Report::class)->group( function () {

        Route::get('invoices_report','index');

        Route::post('Search_invoices','Search_invoices');

        Route::post('export_report_pdf','export_report_pdf')->name('export_report_pdf.pdf');

        Route::get('paid_invoices','paid_invoices');

        Route::get('unpaid_invoices','unpaid_invoices');

    }
);

Route::post('Search_customers', [Customers_Report::class,'Search_customers']);

Route::group(['middleware' => ['auth']], function() {

    Route::resource('roles',RoleController::class);

    Route::resource('users',UserController::class);
});

///////////////////////////////////Start AccountingNotebook Route/////////////////////////////////////
Route::group(['prefix' => 'AccountingNotebook'] , function() {


    // Route::get('/index' , [AccountingNotebookController::class , 'index'])->name('AccountingNotebook.index') ;

    Route::get('/create' , [AccountingNotebookController::class , 'create'])->name('AccountingNotebook.create') ;

    Route::post('/store' , [AccountingNotebookController::class , 'store'])->name('AccountingNotebook.store') ;

    Route::get('/edit/{id}' , [AccountingNotebookController::class , 'edit'])->name('AccountingNotebook.edit') ;

    Route::post('/update' , [AccountingNotebookController::class , 'update'])->name('AccountingNotebook.update') ;

    Route::get('/delete/{id}' , [AccountingNotebookController::class , 'destroy'])->name('AccountingNotebook.delete') ;

    Route::post('search', [AccountingNotebookController::class , 'search_in_accounting'])->name('search_in_accounting');


    // Start Box
    // Route::get('/' , [LanguageController::class , 'index'])->name('admin.language.index') ;

    Route::group([ 'prefix' =>   'box'] , function()    {

        Route::get('/' , [BoxController::class , 'index'])->name('AccountingNotebook.box.index') ;

        Route::get('/create' , [BoxController::class , 'create'])->name('AccountingNotebook.box.create') ;

        Route::post('store' , [BoxController::class , 'store'])->name('AccountingNotebook.box.store') ;

        Route::get('edit/{id}' , [BoxController::class , 'edit'])->name('AccountingNotebook.box.edit') ;

        Route::post('update' , [BoxController::class , 'update'])->name('AccountingNotebook.box.update') ;

        Route::get('/delete/{id}' , [BoxController::class , 'destroy'])->name('AccountingNotebook.box.delete') ;
    }) ;
    // End Box


    // Start SendTo
    Route::group([ 'prefix' =>   'SendTo'] , function()    {

        Route::get('/' , [SendToController::class , 'index'])->name('AccountingNotebook.SendTo.index') ;

        Route::get('/create' , [SendToController::class , 'create'])->name('AccountingNotebook.SendTo.create') ;

        Route::post('store' , [SendToController::class , 'store'])->name('AccountingNotebook.SendTo.store') ;

        Route::get('edit/{id}' , [SendToController::class , 'edit'])->name('AccountingNotebook.SendTo.edit') ;

        Route::post('update' , [SendToController::class , 'update'])->name('AccountingNotebook.SendTo.update') ;

        Route::get('/delete/{id}' , [SendToController::class , 'destroy'])->name('AccountingNotebook.SendTo.delete') ;
    }) ;
    // End SendTo


    // Start LiquidationStatus
    Route::group([ 'prefix' =>   'LiquidationStatus'] , function()    {

        Route::get('/' , [LiquidationStatusController::class , 'index'])->name('AccountingNotebook.LiquidationStatus.index') ;

        Route::get('/create' , [LiquidationStatusController::class , 'create'])->name('AccountingNotebook.LiquidationStatus.create') ;

        Route::post('store' , [LiquidationStatusController::class , 'store'])->name('AccountingNotebook.LiquidationStatus.store') ;

        Route::get('edit/{id}' , [LiquidationStatusController::class , 'edit'])->name('AccountingNotebook.LiquidationStatus.edit') ;

        Route::post('update' , [LiquidationStatusController::class , 'update'])->name('AccountingNotebook.LiquidationStatus.update') ;

        Route::get('/delete/{id}' , [LiquidationStatusController::class , 'destroy'])->name('AccountingNotebook.LiquidationStatus.delete') ;
    }) ;
})  ;
    // #end LiquidationStatus

     // Start Company
Route::prefix('company')->name('company.')->group(function () {

    Route::get('/', [CompanyController::class,'index'])->name('allcompany');

    Route::get('/add-Company', [CompanyController::class,'create'])->name('addCompany');

    Route::post('/add-Company', [CompanyController::class,'store'])->name('addCompany');

    Route::get('/edit-Company/{id}', [CompanyController::class,'edit'])->name('editCompany');

    Route::post('/update-company', [CompanyController::class,'update'])->name('updateCompany');

    Route::get('/delete-company/{id}', [CompanyController::class,'destroy'])->name('destroycompany');
});
    // #end Company

         // Start dftar
    Route::get('/myaccountants', [MyAccountantsController::class,'index'])->name('myaccountants');

    Route::post('/add-myaccountants', [MyAccountantsController::class,'store'])->name('myaccountants.store');

    Route::get('/edit-myaccountants/{id}', [MyAccountantsController::class,'edit'])->name('myaccountants.edit');

    Route::post('/update-myaccountants', [MyAccountantsController::class,'update'])->name('myaccountants.update');

    Route::get('/delete-myaccountants/{id}', [MyAccountantsController::class,'destroy'])->name('myaccountants.delete');

    Route::get('/myaccountants/accountingnotebook/{id}', [MyAccountantsController::class,'create'])->name('addmyaccountants');

    Route::get('/allaccountingnotebook/{id}', [MyAccountantsController::class,'show'])->name('allaccountingnotebook.show');

    // #end dftar

app/Models/invoices.php
<?php

namespace App\Models;
use App\Models\sections;
use App\Http\User;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;

class invoices extends Model
{
  use HasFactory;

    protected $fillable = [
        'invoice_number',
        'invoice_Date',
        'Due_date',
        'supplier_name',
        'price_total',
        'Status',
        'Value_Status',
        'note',
        'Payment_Date',
    ];

    protected $dates = ['deleted_at'];
    public function getfile()
    {
        return  $this->hasOne(invoice_attachments_table::class , 'invoice_id', 'id');
    }
}

app/Http/Controllers/InvoicesController.php
<?php

namespace App\Http\Controllers;

use Proengsoft\JsValidation\Facades\JsValidatorFacade;
use App\Models\invoices;
use App\Models\invoices_detaills;
use App\Models\invoice_attachments_table;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Http\Request;
use App\Exports\InvoicesExport;



class InvoicesController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:الفواتير', ['only' => ['index']]);
        // $this->middleware('can:اضافة فاتورة', ['only' => ['create', 'store']]);
        // $this->middleware('can:تعديل الفاتورة', ['only' => ['edit', 'update']]);
        // $this->middleware('can:حذف الفاتورة', ['only' => ['destroy']]);
        // $this->middleware('can:تغير حالة الدفع', ['only' => ['Status_Update']]);
        // $this->middleware('can:تغير حالة الدفع', ['only' => ['Invoice_Paid']]);
        // $this->middleware('can:تغير حالة الدفع', ['only' => ['Invoice_unPaid']]);
        // $this->middleware('can:طباعةالفاتورة', ['only' => ['Print_invoice']]);
        // $this->middleware('can:تصدير EXCEL', ['only' => ['export']]);
    }

    protected $validationRules = [
        'invoice_number' => 'required',
        'invoice_Date' => 'required',
        'Due_date' => 'required',
        'supplier_name' => 'required',
        'price_total' => 'required',
        'Status' => 'required',
        'Value_Status' => 'required',
        // 'note' => 'required'
    ];

    public function index()
    {
         $invoices = invoices::with(['getfile'])->get();

        return view('invoices.invoices', compact('invoices'));
    }

    public function create()
    {
        //  $sections = sections::all();
        $validator = JsValidatorFacade::make($this->validationRules);
        return view('invoices.add_invoice', compact('validator'));
    }

    public function store(Request $request)
    {
        try {
        invoices::create([
            'invoice_number' => $request->invoice_number,
            'invoice_Date' => $request->invoice_Date,
            'Due_date' => $request->Due_date,
            'supplier_name' => $request->supplier_name,
            'price_total' => $request->price_total,
            'Status' => 'غير مدفوعة',
            'Value_Status' => 2,
            'note' => $request->note,
        ]);
        $invoice_id = invoices::latest()->first()->id;
        invoices_detaills::create([
            'id_Invoice' => $invoice_id,
            'invoice_number' => $request->invoice_number,
            'supplier_name' => $request->supplier_name,
            'Status' => 'غير مدفوعة',
            'Value_Status' => 2,
            'note' => $request->note,
            'user' => (Auth::user()->name),
        ]);
        if ($request->hasFile('pic')) {

            $invoice_id = Invoices::latest()->first()->id;
            $image = $request->file('pic');
            $file_name = $image->getClientOriginalName();
            $invoice_number = $request->invoice_number;

            $attachments = new invoice_attachments_table();
            $attachments->file_name = $file_name;
            $attachments->invoice_number = $invoice_number;
            $attachments->Created_by = Auth::user()->name;
            $attachments->invoice_id = $invoice_id;
            $attachments->save();

            // move pic
            $imageName = $request->pic->getClientOriginalName();
            $request->pic->move(public_path('Attachments/' . $invoice_number), $imageName);
        }

        return redirect()->route('invoices.index')->with('success', 'تم اضافة الفاتورة بنجاح');
    } catch (\Throwable $th) {
        // Redirect with error message
        return redirect()->route('invoices.index')->with(['error' => 'قمت بالاضافة بشكل خاطىء!']);
    }
    }

    public function show($id)
    {
        $invoices = invoices::where('id', $id)->first();
        return view('invoices.status_update', compact('invoices'));
    }

    public function edit($id)
    {
        $invoices = invoices::where('id', $id)->first();
        $validator = JsValidatorFacade::make($this->validationRules);
        return view('invoices.edit_invoice', compact('invoices', 'validator'));
    }

    public function update(Request $request)
    {
        $invoices = invoices::findOrFail($request->invoice_id);
        $invoices->update([
            'invoice_number' => $request->invoice_number,
            'invoice_Date' => $request->invoice_Date,
            'Due_date' => $request->Due_date,
            'supplier_name' => $request->supplier_name,
            'price_total' => $request->price_total,
            'note' => $request->note,
        ]);

        return redirect()->route('invoices.index')->with('edit', 'تم تعديل الفاتورة بنجاح');
    }

    public function destroy(Request $request)
    {
        $id = $request->invoice_id;
        $invoices = invoices::where('id', $id)->first();
        $Details = invoice_attachments_table::where('invoice_id', $id)->first();

        $id_page = $request->id_page;


        if (!$id_page == 2) {

            if (!empty($Details->invoice_number)) {

                Storage::disk('public_uploads')->deleteDirectory($Details->invoice_number);
            }

            $invoices->forceDelete();
            // $invoices->Delete();
            session()->flash('delete_invoice');
            return redirect('/invoices');
        } else {

            $invoices->delete();
            session()->flash('archive_invoice');
            return redirect('/Archive');
        }
    }

    public function Status_Update($id, Request $request)
    {
        $invoices = invoices::findOrFail($id);

        if ($request->Status === 'مدفوعة') {

            $invoices->update([
                'Value_Status' => 1,
                'Status' => $request->Status,
                'Payment_Date' => $request->Payment_Date,
            ]);

            invoices_Detaills::create([
                'id_Invoice' => $request->invoice_id,
                'invoice_number' => $request->invoice_number,
                'Status' => $request->Status,
                'Value_Status' => 1,
                'note' => $request->note,
                'Payment_Date' => $request->Payment_Date,
                'user' => (Auth::user()->name),
            ]);
        } else {
            $invoices->update([
                'Value_Status' => 3,
                'Status' => $request->Status,
                'Payment_Date' => $request->Payment_Date,
            ]);
            invoices_Detaills::create([
                'id_Invoice' => $request->invoice_id,
                'invoice_number' => $request->invoice_number,
                'Status' => $request->Status,
                'Value_Status' => 3,
                'note' => $request->note,
                'Payment_Date' => $request->Payment_Date,
                'user' => (Auth::user()->name),
            ]);
        }
        session()->flash('Status_Update');
        return redirect('/invoices');
    }
    public function Invoice_Paid()
    {
        $invoices = Invoices::where('Value_Status', 1)->get();
        return view('invoices.invoices_paid', compact('invoices'));
    }

    public function Invoice_unPaid()
    {
        $invoices = Invoices::where('Value_Status', 2)->get();
        return view('invoices.invoices_unpaid', compact('invoices'));
    }


    public function Print_invoice($id)
    {
        $invoices = invoices::where('id', $id)->first();
        return view('invoices.Print_invoice', compact('invoices'));
    }

    public function export()
    {
        return Excel::download(new InvoicesExport, 'invoices.xlsx');
    }
}

resources/views/invoices/Print_invoice.blade.php
@extends('layouts.master')
@section('css')
    <style>
        @media print {
            #print_Button {
                display: none;
            }
        }

    </style>
@endsection
@section('title')
    معاينه طباعة الفاتورة
@stop
@section('page-header')
    <!-- breadcrumb -->
    <div class="breadcrumb-header justify-content-between">
        <div class="my-auto">
            <div class="d-flex">
                <h4 class="content-title mb-0 my-auto">الفواتير</h4><span class="text-muted mt-1 tx-13 mr-2 mb-0">/
                    معاينة طباعة الفاتورة</span>
            </div>
        </div>

    </div>
    <!-- breadcrumb -->
@endsection
@section('content')
    <!-- row -->
    <div class="row row-sm">
        <div class="col-md-12 col-xl-12">
            <div class=" main-content-body-invoice" id="print">
                <div class="card card-invoice">
                    <div class="card-body">
                        <div class="invoice-header">
                            <h1 class="invoice-title">فاتورة تحصيل</h1>
                            <div class="billed-from">
                                <h6>Inc.Clouds Zone</h6>
                                <p>Al Makarunah Street , Jeddah 23337<br>
                                    Tel No: +966548689528<br>
                                    Email: Info@cloudszone.net</p>
                            </div><!-- billed-from -->
                        </div><!-- invoice-header -->
                        <div class="row mg-t-20">
                            <div class="col-md">
                                <label class="tx-gray-600">Billed To</label>
                                <div class="billed-to">
                                    <h6>Inc.Clouds Zone</h6>
                                    <p>Al Makarunah Street , Jeddah 23337<br>
                                        Tel No:  +966548689528<br>
                                        Email: Info@cloudszone.net</p>
                                </div>
                            </div>
                            <div class="col-md">
                                <label class="tx-gray-600">معلومات الفاتورة</label>
                                <p class="invoice-info-row"><span>رقم الفاتورة</span>
                                    <span>{{ $invoices->invoice_number }}</span></p>
                                <p class="invoice-info-row"><span>تاريخ الاصدار</span>
                                    <span>{{ $invoices->invoice_Date }}</span></p>
                                <p class="invoice-info-row"><span>تاريخ الاستحقاق</span>
                                    <span>{{ $invoices->Due_date }}</span></p>
                                <p class="invoice-info-row"><span>اسم المورد</span>
                                    <span>{{ $invoices->supplier_name }}</span></p>

                            </div>
                        </div>
                        <div class="table-responsive mg-t-40">
                            <table class="table table-invoice border text-md-nowrap mb-0">
                                <thead>
                                    <tr>
                                        <th class="wd-20p">#</th>
                                        <th class="tx-right">الاجمالي</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td class="tx-right tx-uppercase tx-bold tx-inverse">المبلغ الاجمالي   </td>
                                        <td class="tx-right" colspan="2">
                                            <h4 class="tx-primary tx-bold">{{ $invoices->price_total }}</h4>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <hr class="mg-b-40">



                        <button class="btn btn-danger  float-left mt-3 mr-2" id="print_Button" onclick="printDiv()"> <i
                                class="mdi mdi-printer ml-1"></i>طباعة</button>
                    </div>
                </div>
            </div>
        </div><!-- COL-END -->
    </div>
    <!-- row closed -->
    </div>
    <!-- Container closed -->
    </div>
    <!-- main-content closed -->
@endsection
@section('js')
    <!--Internal  Chart.bundle js -->
    <script src="{{ URL::asset('assets/plugins/chart.js/Chart.bundle.min.js') }}"></script>


    <script type="text/javascript">
        function printDiv() {
            var printContents = document.getElementById('print').innerHTML;
            var originalContents = document.body.innerHTML;
            document.body.innerHTML = printContents;
            window.print();
            document.body.innerHTML = originalContents;
            location.reload();
        }

    </script>

@endsection

resources/views/invoices/add_invoice.blade.php
@extends('layouts.master')
@section('css')
    <!--- Internal Select2 css-->
    <link href="{{ URL::asset('assets/plugins/select2/css/select2.min.css') }}" rel="stylesheet">
    <!---Internal Fileupload css-->
    <link href="{{ URL::asset('assets/plugins/fileuploads/css/fileupload.css') }}" rel="stylesheet" type="text/css" />
    <!---Internal Fancy uploader css-->
    <link href="{{ URL::asset('assets/plugins/fancyuploder/fancy_fileupload.css') }}" rel="stylesheet" />
    <!--Internal Sumoselect css-->
    <link rel="stylesheet" href="{{ URL::asset('assets/plugins/sumoselect/sumoselect-rtl.css') }}">
    <!--Internal  TelephoneInput css-->
    <link rel="stylesheet" href="{{ URL::asset('assets/plugins/telephoneinput/telephoneinput-rtl.css') }}">
@endsection
@section('title')
    اضافة فاتورة
@stop

@section('page-header')
    <!-- breadcrumb -->
    <div class="breadcrumb-header justify-content-between">
        <div class="my-auto">
            <div class="d-flex">
                <h4 class="content-title mb-0 my-auto">الفواتير</h4><span class="text-muted mt-1 tx-13 mr-2 mb-0">/
                    اضافة فاتورة</span>
            </div>
        </div>
    </div>
    <!-- breadcrumb -->
@endsection
@section('content')

    @if (session()->has('Add'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>{{ session()->get('Add') }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="card-body">
                    <form id="formInvoice" action="{{ route('invoices.store') }}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        {{-- 1 --}}
                        <div class="row">
                            <div class="col">
                                <label for="inputName" class="control-label">رقم الفاتورة</label>
                                <input type="text" class="form-control" id="inputName" name="invoice_number"
                                    title="يرجي ادخال رقم الفاتورة" required>
                            </div>

                            <div class="col">
                                <label>تاريخ الفاتورة</label>
                                <input class="form-control" id="invoice_Date" name="invoice_Date" placeholder="YYYY-MM-DD"
                                    type="date" value="{{ date('Y-m-d') }}" required>
                            </div>

                            <div class="col">
                                <label>تاريخ الاستحقاق</label>
                                <input class="form-control" name="Due_date" placeholder="YYYY-MM-DD"
                                    type="date">
                            </div>

                        </div>

                        <div class="row">

                            <div class="col">
                                <label for="inputName" class="control-label">الاجمالي شامل </label>
                                <input type="Number" class="form-control" id="price_total" name="price_total">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <label for="exampleTextarea">اسم المورد</label>
                                <input type="text" class="form-control" id="supplier_name" name="supplier_name">
                            </div>
                        </div>
                        <br>

                        {{-- 5 --}}
                        <div class="row">
                            <div class="col">
                                <label>ملاحظات</label>
                                <textarea class="form-control" id="exampleTextarea" name="note" rows="3"></textarea>
                            </div>
                        </div><br>

                        <p class="text-danger">* صيغة المرفق pdf, jpeg ,.jpg , png </p>
                        <h5 class="card-title">المرفقات</h5>

                        <div class="col-sm-12 col-md-12">
                            <input type="file" name="pic" class="dropify" accept=".pdf,.jpg, .png, image/jpeg, image/png"
                                data-height="70" />
                        </div><br>

                        <div class="d-flex justify-content-center">
                            <button type="submit" class="btn btn-primary">حفظ البيانات</button>
                        </div>


                    </form>
                </div>
            </div>
        </div>
    </div>

    </div>

    <!-- row closed -->
    </div>
    <!-- Container closed -->
    </div>
    <!-- main-content closed -->
@endsection
@section('js')
{!! $validator->selector('#formInvoice') !!}
    <!-- Internal Select2 js-->
    <script src="{{ URL::asset('assets/plugins/select2/js/select2.min.js') }}"></script>
    <!--Internal Fileuploads js-->
    <script src="{{ URL::asset('assets/plugins/fileuploads/js/fileupload.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/fileuploads/js/file-upload.js') }}"></script>
    <!--Internal Fancy uploader js-->
    <script src="{{ URL::asset('assets/plugins/fancyuploder/jquery.ui.widget.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/fancyuploder/jquery.fileupload.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/fancyuploder/jquery.iframe-transport.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/fancyuploder/jquery.fancy-fileupload.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/fancyuploder/fancy-uploader.js') }}"></script>
    <!--Internal  Form-elements js-->
    <script src="{{ URL::asset('assets/js/advanced-form-elements.js') }}"></script>
    <script src="{{ URL::asset('assets/js/select2.js') }}"></script>
    <!--Internal Sumoselect js-->
    <script src="{{ URL::asset('assets/plugins/sumoselect/jquery.sumoselect.js') }}"></script>
    <!--Internal  Datepicker js -->
    <script src="{{ URL::asset('assets/plugins/jquery-ui/ui/widgets/datepicker.js') }}"></script>
    <!--Internal  jquery.maskedinput js -->
    <script src="{{ URL::asset('assets/plugins/jquery.maskedinput/jquery.maskedinput.js') }}"></script>
    <!--Internal  spectrum-colorpicker js -->
    <script src="{{ URL::asset('assets/plugins/spectrum-colorpicker/spectrum.js') }}"></script>
    <!-- Internal form-elements js -->
    <script src="{{ URL::asset('assets/js/form-elements.js') }}"></script>

    <script>
        var date = $('.fc-datepicker').datepicker({
            dateFormat: 'yy-mm-dd'
        }).val();

    </script>


@endsection